apiVersion: v1
kind: Service
metadata:
  name: todo-backend
  labels:
    app: todo-backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: todo-backend
