apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
  labels:
    app: todo-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: todo-frontend
